### PR TITLE
Build x86_64 wheels for Pythons 3.7-3.10 with GitHub Actions

### LINKED ISSUE #72: Upgrade curl to 7.80.0
The version which is currently being used by rasterio (7.79.1)  has problems with Letsencrypt certificates:
```
$ rio info https://demo.nextgis.com/api/resource/5511/cog
WARNING:rasterio._env:CPLE_AppDefined in HTTP response code on https://demo.nextgis.com/api/resource/5511/cog.xml: 0
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 261, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 216, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_HttpResponseError: CURL error: SSL certificate problem: certificate has expired
```
It seems the issue has been [fixed](https://github.com/curl/curl/commit/85f91248cffb22d151d5983c32f0dbf6b1de572a) in the recent version (7.80.0) of curl.

### PR DESCRIPTION
**Pull request by sgillies**
Resolves #72 and #73.

Inspired by the pillow-wheels project.

Required some version updrades and a TIFF patch.

### CODE REVIEW

**Comment by rbuffat** [comment]
@sgillies 

There is a github action you can use to ssh into the github session, this can be very convenient while debugging: https://github.com/marketplace/actions/debugging-with-ssh

**Comment by sgillies** [comment]
@vincentsarago @snowman2 yes? no?

**Review by snowman2 — APPROVED** [review]

**Comment by snowman2** [comment]
Why did HDF5 get removed?

**Comment by snowman2** [comment]
Was HDF5 removed for OSX issues? If so, can it be kept in for Linux? I use HDF/netCDF regularly and would be sad to see it go.

**Comment by sgillies** [comment]
@snowman2 it's still there, I only removed the major customizations (incomplete) for macosx arm64 and reverted to vanilla multibuild.

**Comment by snowman2** [comment]
Oh good. Then I think that this is good to go 👍

**Comment by snowman2** [comment]
Nice work!

**Pull request merged**
