### PR TITLE
Rel 1.3.8.post1

### PR DESCRIPTION
**Pull request by sgillies**

### CODE REVIEW

**Comment by sgillies** [comment]
Reverting to Cython < 3 didn't work. I still see the segmentation fault in test_compdcs.

**Comment by sgillies** [comment]
Hold on, Windows wheels tests passed for Python 3.8-3.11 after reverting to Cython 0.29: https://github.com/rasterio/rasterio-wheels/actions/runs/6237503716.

**Comment by sgillies** [comment]
@snowman2 thanks for spotting the problem! Indeed, removing the extra instance of `_matches` prevents the segmentation fault on Linux. I'm testing Windows now.

**Comment by snowman2** [comment]
> @snowman2 thanks for spotting the problem! Indeed, removing the extra instance of `_matches` prevents the segmentation fault on Linux. I'm testing Windows now.

I am glad that it addressed the issue. That one was a challenge to find 😀

**Pull request merged**
